//! OAuth-specific security functions.
//!
//! Provides OAuth token encryption and PKCE (Proof Key for Code Exchange) generation.

use anyhow::Result;
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
use ring::rand::{SecureRandom, SystemRandom};
use sha2::{Digest, Sha256};

/// Minimum code verifier length (RFC 7636 requires 43-128 characters)
const MIN_VERIFIER_LENGTH: usize = 43;

/// Maximum code verifier length
const MAX_VERIFIER_LENGTH: usize = 128;

/// Default code verifier length (64 bytes = ~86 URL-safe base64 characters)
const DEFAULT_VERIFIER_LENGTH: usize = 64;

/// Generates a cryptographically secure PKCE code verifier.
///
/// PKCE (Proof Key for Code Exchange) is used in mobile OAuth flows to prevent
/// authorization code interception attacks.
///
/// # Arguments
///
/// * `length` - Length of random bytes (default: 64, resulting in ~86 characters)
///
/// # Returns
///
/// * `Result<String>` - URL-safe base64 encoded code verifier
///
/// # Security
///
/// - Uses SystemRandom (CSPRNG) for cryptographically secure random generation
/// - URL-safe base64 encoding (no padding)
/// - Length validates against RFC 7636 requirements (43-128 characters)
///
/// # Example
///
/// ```rust
/// let code_verifier = generate_pkce_code_verifier()?;
/// println!("Code verifier: {}", code_verifier);
/// // Output: ~86 character URL-safe base64 string
/// ```
pub fn generate_pkce_code_verifier() -> Result<String> {
    let rng = SystemRandom::new();
    let mut bytes = vec![0u8; DEFAULT_VERIFIER_LENGTH];

    rng.fill(&mut bytes)
        .map_err(|_| anyhow::anyhow!("Failed to generate secure random bytes"))?;

    // Encode as URL-safe base64 (no padding)
    let verifier = URL_SAFE_NO_PAD.encode(&bytes);

    // Validate length (RFC 7636: 43-128 characters)
    if verifier.len() < MIN_VERIFIER_LENGTH || verifier.len() > MAX_VERIFIER_LENGTH {
        anyhow::bail!(
            "Generated verifier length {} out of range ({}-{})",
            verifier.len(),
            MIN_VERIFIER_LENGTH,
            MAX_VERIFIER_LENGTH
        );
    }

    Ok(verifier)
}

/// Generates a PKCE code challenge from a code verifier.
///
/// Uses SHA-256 hash as per RFC 7636 recommendations (more secure than plain method).
///
/// # Arguments
///
/// * `code_verifier` - The code verifier generated by `generate_pkce_code_verifier`
///
/// # Returns
///
/// * `Result<String>` - URL-safe base64 encoded code challenge (SHA-256 hash)
///
/// # Example
///
/// ```rust
/// let verifier = generate_pkce_code_verifier()?;
/// let challenge = generate_pkce_code_challenge(&verifier)?;
///
/// // Send challenge to OAuth provider
/// // Keep verifier on client
/// ```
pub fn generate_pkce_code_challenge(code_verifier: &str) -> Result<String> {
    // Validate verifier length
    if code_verifier.len() < MIN_VERIFIER_LENGTH
        || code_verifier.len() > MAX_VERIFIER_LENGTH
    {
        anyhow::bail!(
            "Code verifier length {} out of range ({}-{})",
            code_verifier.len(),
            MIN_VERIFIER_LENGTH,
            MAX_VERIFIER_LENGTH
        );
    }

    // SHA-256 hash the verifier
    let mut hasher = Sha256::new();
    hasher.update(code_verifier.as_bytes());
    let hash = hasher.finalize();

    // Encode as URL-safe base64 (no padding)
    let challenge = URL_SAFE_NO_PAD.encode(hash);

    Ok(challenge)
}

/// Generates a matched PKCE code verifier and code challenge pair.
///
/// Convenience function that generates both the verifier and its corresponding challenge.
///
/// # Returns
///
/// * `Result<(String, String)>` - Tuple of (code_verifier, code_challenge)
///
/// # Example
///
/// ```rust
/// let (verifier, challenge) = generate_pkce_pair()?;
///
/// // Store verifier on client (or in session)
/// // Send challenge to OAuth authorization endpoint
/// ```
pub fn generate_pkce_pair() -> Result<(String, String)> {
    let verifier = generate_pkce_code_verifier()?;
    let challenge = generate_pkce_code_challenge(&verifier)?;

    Ok((verifier, challenge))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_pkce_code_verifier() {
        let verifier = generate_pkce_code_verifier().unwrap();

        // Should be URL-safe base64
        assert!(verifier.chars().all(|c| c.is_alphanumeric() || c == '-' || c == '_'));

        // Should be within valid length range
        assert!(verifier.len() >= MIN_VERIFIER_LENGTH);
        assert!(verifier.len() <= MAX_VERIFIER_LENGTH);
    }

    #[test]
    fn test_generate_pkce_code_verifier_unique() {
        let verifier1 = generate_pkce_code_verifier().unwrap();
        let verifier2 = generate_pkce_code_verifier().unwrap();

        // Should generate different verifiers
        assert_ne!(verifier1, verifier2);
    }

    #[test]
    fn test_generate_pkce_code_challenge() {
        let verifier = generate_pkce_code_verifier().unwrap();
        let challenge = generate_pkce_code_challenge(&verifier).unwrap();

        // Should be URL-safe base64
        assert!(challenge
            .chars()
            .all(|c| c.is_alphanumeric() || c == '-' || c == '_'));

        // Challenge should be deterministic for same verifier
        let challenge2 = generate_pkce_code_challenge(&verifier).unwrap();
        assert_eq!(challenge, challenge2);

        // Different verifiers should produce different challenges
        let verifier3 = generate_pkce_code_verifier().unwrap();
        let challenge3 = generate_pkce_code_challenge(&verifier3).unwrap();
        assert_ne!(challenge, challenge3);
    }

    #[test]
    fn test_generate_pkce_code_challenge_invalid_verifier() {
        // Too short
        let result = generate_pkce_code_challenge("short");
        assert!(result.is_err());

        // Too long
        let long_verifier = "a".repeat(MAX_VERIFIER_LENGTH + 1);
        let result = generate_pkce_code_challenge(&long_verifier);
        assert!(result.is_err());
    }

    #[test]
    fn test_generate_pkce_pair() {
        let (verifier, challenge) = generate_pkce_pair().unwrap();

        // Verifier should be valid
        assert!(verifier.len() >= MIN_VERIFIER_LENGTH);
        assert!(verifier.len() <= MAX_VERIFIER_LENGTH);

        // Challenge should match verifier
        let expected_challenge = generate_pkce_code_challenge(&verifier).unwrap();
        assert_eq!(challenge, expected_challenge);
    }

    #[test]
    fn test_pkce_challenge_is_sha256() {
        let verifier = "test_code_verifier_with_exactly_43_characters";
        let challenge = generate_pkce_code_challenge(verifier).unwrap();

        // Manually compute expected SHA-256 hash
        let mut hasher = Sha256::new();
        hasher.update(verifier.as_bytes());
        let expected_hash = hasher.finalize();
        let expected_challenge = URL_SAFE_NO_PAD.encode(expected_hash);

        assert_eq!(challenge, expected_challenge);
    }

    #[test]
    fn test_pkce_verifier_length_distribution() {
        // Generate 100 verifiers and check they're all in valid range
        for _ in 0..100 {
            let verifier = generate_pkce_code_verifier().unwrap();
            assert!(verifier.len() >= MIN_VERIFIER_LENGTH);
            assert!(verifier.len() <= MAX_VERIFIER_LENGTH);
        }
    }
}
