# Generated by Django 6.0.3 on 2026-03-13 13:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syntek_auth", "0006_encrypt_token_jti_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pendingoauthsession",
            new_name="syntek_auth_expires_8719e3_idx",
            old_name="syntek_pending_oauth_exp_idx",
        ),
        migrations.AlterField(
            model_name="accesstokendenylist",
            name="jti_token",
            field=models.CharField(
                db_index=True,
                help_text="HMAC-SHA256 of the plaintext JTI.  Use this column for lookups — never filter on the ciphertext.",
                max_length=64,
                unique=True,
                verbose_name="JTI lookup token",
            ),
        ),
        migrations.AlterField(
            model_name="pendingoauthsession",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="jti_token",
            field=models.CharField(
                db_index=True,
                help_text="HMAC-SHA256 of the plaintext JTI.  Use this column for lookups — never filter on the ciphertext.",
                max_length=64,
                unique=True,
                verbose_name="JTI lookup token",
            ),
        ),
        migrations.AlterField(
            model_name="verificationcode",
            name="token_token",
            field=models.CharField(
                db_index=True,
                help_text="HMAC-SHA256 of the plaintext verification token.  Use this column for lookups — never filter on the ciphertext.",
                max_length=64,
                unique=True,
                verbose_name="token lookup token",
            ),
        ),
    ]
