# Generated by Django 6.0.4 on 2026-03-13

from django.db import migrations, models

import syntek_auth.models.user


class Migration(migrations.Migration):
    dependencies = [
        (
            "syntek_auth",
            "0007_rename_syntek_pending_oauth_exp_idx_syntek_auth_expires_8719e3_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=syntek_auth.models.user.EncryptedField(
                blank=True,
                null=True,
                verbose_name="TOTP secret",
                help_text=(
                    "AES-256-GCM encrypted base32-encoded TOTP secret for RFC 6238 "
                    "authenticator apps.  Null until the user enables TOTP."
                ),
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_secret_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text=(
                    "HMAC-SHA256 of the plaintext TOTP secret.  Enforces uniqueness "
                    "across users — no two accounts may share the same TOTP seed."
                ),
                max_length=64,
                null=True,
                unique=True,
                verbose_name="TOTP secret token",
            ),
        ),
    ]
