//! Configuration templates for authentication setup
//!
//! Generates Django settings, environment files, and documentation.

use crate::config::auth_config::{AuthConfig, SocialProviderConfig};
use std::collections::HashMap;

/// Generate Django settings TOML
pub fn django_settings_toml(config: &AuthConfig) -> String {
    format!(
        r#"# Syntek Authentication Configuration
# Generated by syntek-cli

[SYNTEK_AUTH]
# Installation mode: {}
MODE = "{}"

# Email encryption
EMAIL_ENCRYPTION_KEY = "${{EMAIL_ENCRYPTION_KEY}}"

# Rate limiting
[SYNTEK_AUTH.RATE_LIMITING]
register_requests = {}
register_window_seconds = {}
login_requests = {}
login_window_seconds = {}
password_reset_requests = {}
password_reset_window_seconds = {}
verify_email_requests = {}
verify_email_window_seconds = {}

# Constant-time responses
[SYNTEK_AUTH.CONSTANT_TIME]
target_time_ms = {}
log_variance = {}
variance_alert_threshold_ms = {}
endpoints = [{}]

# Session fingerprinting
[SYNTEK_AUTH.FINGERPRINTING]
level = "{}"
require_consent = {}
privacy_transparency = {}

# Argon2id password hashing
[SYNTEK_AUTH.ARGON2]
memory_kib = {}
iterations = {}
parallelism = {}
auto_tune = {}

# Backup codes
[SYNTEK_AUTH.BACKUP_CODES]
count = {}
length = {}
expiry_days = {}

# SMS cost attack prevention
[SYNTEK_AUTH.SMS_COST_PREVENTION]
global_rate_limit = {}
daily_budget_limit = {}
captcha_threshold = {}
auto_block = {}

[SYNTEK_AUTH.SMS_COST_PREVENTION.cost_per_sms]
twilio = {}
aws_sns = {}
vonage = {}

[SYNTEK_AUTH.SMS_COST_PREVENTION.alert_thresholds]
values = [{}]
destinations = [{}]

# GDPR compliance
[SYNTEK_AUTH.GDPR]
legal_region = "{}"
privacy_policy_version = "{}"
terms_version = "{}"
legal_docs_path = "{}"
data_retention_days = {}
ip_log_retention_days = {}
deletion_grace_period_days = {}
consent_audit = {}
pii_access_logging = {}
key_rotation_days = {}

{}
"#,
        config.mode,
        config.mode,
        config.rate_limiting.get("register").map_or(5, |r| r.requests),
        config.rate_limiting.get("register").map_or(3600, |r| r.window_seconds),
        config.rate_limiting.get("login").map_or(10, |r| r.requests),
        config.rate_limiting.get("login").map_or(600, |r| r.window_seconds),
        config
            .rate_limiting
            .get("password_reset")
            .map_or(3, |r| r.requests),
        config
            .rate_limiting
            .get("password_reset")
            .map_or(3600, |r| r.window_seconds),
        config
            .rate_limiting
            .get("verify_email")
            .map_or(5, |r| r.requests),
        config
            .rate_limiting
            .get("verify_email")
            .map_or(3600, |r| r.window_seconds),
        config.constant_time.target_time_ms,
        config.constant_time.log_variance,
        config.constant_time.variance_alert_threshold_ms,
        config
            .constant_time
            .endpoints
            .iter()
            .map(|e| format!("\"{}\"", e))
            .collect::<Vec<_>>()
            .join(", "),
        config.fingerprinting.level,
        config.fingerprinting.require_consent,
        config.fingerprinting.privacy_transparency,
        config.argon2.memory_kib,
        config.argon2.iterations,
        config.argon2.parallelism,
        config.argon2.auto_tune,
        config.backup_codes.count,
        config.backup_codes.length,
        config.backup_codes.expiry_days,
        config.sms_cost_prevention.global_rate_limit,
        config.sms_cost_prevention.daily_budget_limit,
        config.sms_cost_prevention.captcha_threshold,
        config.sms_cost_prevention.auto_block,
        config
            .sms_cost_prevention
            .cost_per_sms
            .get("twilio")
            .unwrap_or(&0.0075),
        config
            .sms_cost_prevention
            .cost_per_sms
            .get("aws_sns")
            .unwrap_or(&0.00645),
        config
            .sms_cost_prevention
            .cost_per_sms
            .get("vonage")
            .unwrap_or(&0.0072),
        config
            .sms_cost_prevention
            .alert_thresholds
            .iter()
            .map(|t| t.to_string())
            .collect::<Vec<_>>()
            .join(", "),
        config
            .sms_cost_prevention
            .alert_destinations
            .iter()
            .map(|d| format!("\"{}\"", d))
            .collect::<Vec<_>>()
            .join(", "),
        config.gdpr.legal_region,
        config.gdpr.privacy_policy_version,
        config.gdpr.terms_version,
        config.gdpr.legal_docs_path,
        config.gdpr.data_retention_days,
        config.gdpr.ip_log_retention_days,
        config.gdpr.deletion_grace_period_days,
        config.gdpr.consent_audit,
        config.gdpr.pii_access_logging,
        config.gdpr.key_rotation_days,
        generate_social_auth_config(&config.social_providers)
    )
}

/// Generate social auth configuration section
fn generate_social_auth_config(providers: &[SocialProviderConfig]) -> String {
    if providers.is_empty() {
        return String::new();
    }

    let mut sections = vec!["# Social authentication providers".to_string()];

    for provider in providers {
        sections.push(format!(
            r#"
[SYNTEK_AUTH.SOCIAL_AUTH.{}]
client_id = "{}"
client_secret = "{}"
redirect_uri = "{}"
scopes = [{}]
"#,
            provider.name.to_uppercase(),
            provider.client_id,
            provider.client_secret,
            provider.redirect_uri,
            provider
                .scopes
                .iter()
                .map(|s| format!("\"{}\"", s))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }

    sections.join("\n")
}

/// Generate .env template
pub fn env_template(config: &AuthConfig) -> String {
    let mut lines = vec![
        "# Syntek Authentication Environment Variables".to_string(),
        "# Generated by syntek-cli".to_string(),
        "# IMPORTANT: Replace all placeholder values before deploying".to_string(),
        "".to_string(),
        "# Email encryption (32-byte base64-encoded key)".to_string(),
        format!("EMAIL_ENCRYPTION_KEY={}", config.email_encryption_key),
        "".to_string(),
        "# OpenBao secrets management (optional)".to_string(),
        "OPENBAO_ADDR=http://localhost:8200".to_string(),
        "OPENBAO_TOKEN=your_openbao_token_here".to_string(),
        "".to_string(),
        "# SMS cost prevention alert destinations".to_string(),
        "SMS_ALERT_EMAIL=security@example.com".to_string(),
        "SMS_ALERT_SLACK_WEBHOOK=https://hooks.slack.com/services/YOUR/WEBHOOK/HERE".to_string(),
        "".to_string(),
    ];

    // Add social provider credentials
    if !config.social_providers.is_empty() {
        lines.push("# Social authentication credentials".to_string());
        for provider in &config.social_providers {
            lines.push(format!(
                "{}_CLIENT_ID=your_{}_client_id",
                provider.name.to_uppercase(),
                provider.name
            ));
            lines.push(format!(
                "{}_CLIENT_SECRET=your_{}_client_secret",
                provider.name.to_uppercase(),
                provider.name
            ));
        }
        lines.push("".to_string());
    }

    lines.push("# Django secret key (generate with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())')".to_string());
    lines.push("SECRET_KEY=your_django_secret_key_here".to_string());

    lines.join("\n")
}

/// Generate README for configuration setup
pub fn configuration_readme(config: &AuthConfig) -> String {
    format!(
        r#"# Syntek Authentication Configuration

This directory contains the configuration files for Syntek Authentication.

## Installation Mode

**Mode:** {}

## Configuration Files

- `settings.toml` - Django authentication settings
- `.env` - Environment variables (secrets)
- `.env.example` - Template for environment variables

## Setup Steps

### 1. Configure Environment Variables

Copy `.env.example` to `.env` and replace all placeholder values:

```bash
cp .env.example .env
```

**Required variables:**
- `EMAIL_ENCRYPTION_KEY` - 32-byte base64-encoded key (already generated)
- `SECRET_KEY` - Django secret key

**Optional variables (if using OpenBao):**
- `OPENBAO_ADDR` - OpenBao server address
- `OPENBAO_TOKEN` - OpenBao authentication token

### 2. Social Authentication Setup

{}

### 3. SMS Cost Attack Prevention

Configure alert destinations in `.env`:
- `SMS_ALERT_EMAIL` - Email for budget alerts
- `SMS_ALERT_SLACK_WEBHOOK` - Slack webhook URL

**Current limits:**
- Global rate limit: {} SMS/hour
- Daily budget limit: ${:.2}
- CAPTCHA threshold: {} SMS/hour
- Auto-blocking: {}

### 4. GDPR Compliance

**Legal region:** {}

Update legal documents in `{}`
- Privacy policy version: {}
- Terms of service version: {}

**Data retention:**
- User data: {} days
- IP logs: {} days
- Account deletion grace period: {} days
- Encryption key rotation: {} days

### 5. Django Integration

Add to your Django `settings.py`:

```python
# Load Syntek authentication config
import toml

with open('config/auth/settings.toml') as f:
    syntek_auth_config = toml.load(f)
    SYNTEK_AUTH = syntek_auth_config['SYNTEK_AUTH']

# Add to INSTALLED_APPS
INSTALLED_APPS = [
    # ... other apps
    'syntek_security_core',
    'syntek_security_auth',
    'syntek_authentication',
]
```

### 6. GraphQL Schema

Import authentication mutations and queries:

```python
from syntek_graphql_auth.mutations.auth import AuthMutations
from syntek_graphql_auth.queries.user import UserQueries

@strawberry.type
class Query(UserQueries):
    pass

@strawberry.type
class Mutation(AuthMutations):
    pass
```

### 7. Run Migrations

```bash
python manage.py migrate syntek_authentication
```

### 8. Verification

Run the verification command to check installation:

```bash
syntek verify auth
```

## Security Checklist

- [ ] `.env` file permissions set to 0600
- [ ] `EMAIL_ENCRYPTION_KEY` is unique (not the example value)
- [ ] Django `SECRET_KEY` is unique
- [ ] Social auth credentials configured (if enabled)
- [ ] SMS alert destinations configured
- [ ] Legal documents updated for your region
- [ ] OpenBao configured for production secrets
- [ ] All rate limits reviewed and adjusted

## Rate Limiting

| Endpoint | Limit |
|----------|-------|
| Register | {}/hour |
| Login | {}/10min |
| Password Reset | {}/hour |
| Verify Email | {}/hour |

## Constant-Time Responses

Target response time: {}ms

Applied to endpoints:
{}

## Session Fingerprinting

- Level: {}
- GDPR consent required: {}
- Privacy transparency: {}

## Password Hashing (Argon2id)

- Memory: {} KiB ({} MiB)
- Iterations: {}
- Parallelism: {}
- Auto-tune: {}

## Backup Codes

- Count: {} codes per user
- Length: {} characters
- Expiry: {} days

## Support

For issues or questions, see:
- Documentation: `/docs/authentication/`
- Security: `/docs/security/AUTHENTICATION-SECURITY.md`
- GDPR: `/docs/security/GDPR-COMPLIANCE.md`
"#,
        config.mode,
        generate_social_auth_setup(&config.social_providers),
        config.sms_cost_prevention.global_rate_limit,
        config.sms_cost_prevention.daily_budget_limit,
        config.sms_cost_prevention.captcha_threshold,
        config.sms_cost_prevention.auto_block,
        config.gdpr.legal_region,
        config.gdpr.legal_docs_path,
        config.gdpr.privacy_policy_version,
        config.gdpr.terms_version,
        config.gdpr.data_retention_days,
        config.gdpr.ip_log_retention_days,
        config.gdpr.deletion_grace_period_days,
        config.gdpr.key_rotation_days,
        config.rate_limiting.get("register").map_or(5, |r| r.requests),
        config.rate_limiting.get("login").map_or(10, |r| r.requests),
        config
            .rate_limiting
            .get("password_reset")
            .map_or(3, |r| r.requests),
        config
            .rate_limiting
            .get("verify_email")
            .map_or(5, |r| r.requests),
        config.constant_time.target_time_ms,
        config
            .constant_time
            .endpoints
            .iter()
            .map(|e| format!("- {}", e))
            .collect::<Vec<_>>()
            .join("\n"),
        config.fingerprinting.level,
        config.fingerprinting.require_consent,
        config.fingerprinting.privacy_transparency,
        config.argon2.memory_kib,
        config.argon2.memory_kib / 1024,
        config.argon2.iterations,
        config.argon2.parallelism,
        config.argon2.auto_tune,
        config.backup_codes.count,
        config.backup_codes.length,
        config.backup_codes.expiry_days,
    )
}

/// Generate social auth setup instructions
fn generate_social_auth_setup(providers: &[SocialProviderConfig]) -> String {
    if providers.is_empty() {
        return "No social authentication providers enabled.".to_string();
    }

    let mut setup = vec!["Configure social authentication providers:".to_string(), "".to_string()];

    for provider in providers {
        let guide = match provider.name.as_str() {
            "google" => GOOGLE_SETUP_GUIDE,
            "github" => GITHUB_SETUP_GUIDE,
            "microsoft" => MICROSOFT_SETUP_GUIDE,
            "apple" => APPLE_SETUP_GUIDE,
            "facebook" => FACEBOOK_SETUP_GUIDE,
            "linkedin" => LINKEDIN_SETUP_GUIDE,
            "twitter" | "x" => TWITTER_SETUP_GUIDE,
            _ => "Provider setup guide not available.",
        };

        setup.push(format!("#### {}\n", provider.name.to_uppercase()));
        setup.push(guide.to_string());
        setup.push("".to_string());
    }

    setup.join("\n")
}

const GOOGLE_SETUP_GUIDE: &str = r#"1. Go to https://console.cloud.google.com/apis/credentials
2. Create OAuth 2.0 Client ID
3. Set authorized redirect URI: `https://yourdomain.com/auth/callback/google`
4. Copy Client ID and Client Secret to `.env`:
   - `GOOGLE_CLIENT_ID=your_client_id`
   - `GOOGLE_CLIENT_SECRET=your_client_secret`
5. Required scopes: `openid`, `email`, `profile`"#;

const GITHUB_SETUP_GUIDE: &str = r#"1. Go to https://github.com/settings/developers
2. Create new OAuth App
3. Set callback URL: `https://yourdomain.com/auth/callback/github`
4. Copy Client ID and Client Secret to `.env`:
   - `GITHUB_CLIENT_ID=your_client_id`
   - `GITHUB_CLIENT_SECRET=your_client_secret`
5. Required scopes: `user:email`"#;

const MICROSOFT_SETUP_GUIDE: &str = r#"1. Go to https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps
2. Register new application
3. Add redirect URI: `https://yourdomain.com/auth/callback/microsoft`
4. Create client secret in Certificates & secrets
5. Copy Application (client) ID and secret to `.env`:
   - `MICROSOFT_CLIENT_ID=your_client_id`
   - `MICROSOFT_CLIENT_SECRET=your_client_secret`
6. Required scopes: `openid`, `email`, `profile`"#;

const APPLE_SETUP_GUIDE: &str = r#"1. Go to https://developer.apple.com/account/resources/identifiers
2. Create new Services ID
3. Configure Sign in with Apple
4. Add return URL: `https://yourdomain.com/auth/callback/apple`
5. Create private key and download
6. Copy Services ID and configure `.env`:
   - `APPLE_CLIENT_ID=your_services_id`
   - `APPLE_CLIENT_SECRET=your_private_key_jwt`
7. Required scopes: `name`, `email`"#;

const FACEBOOK_SETUP_GUIDE: &str = r#"1. Go to https://developers.facebook.com/apps
2. Create new app
3. Add Facebook Login product
4. Set valid OAuth redirect URI: `https://yourdomain.com/auth/callback/facebook`
5. Copy App ID and App Secret to `.env`:
   - `FACEBOOK_CLIENT_ID=your_app_id`
   - `FACEBOOK_CLIENT_SECRET=your_app_secret`
6. Required scopes: `email`, `public_profile`"#;

const LINKEDIN_SETUP_GUIDE: &str = r#"1. Go to https://www.linkedin.com/developers/apps
2. Create new app
3. Add OAuth 2.0 redirect URL: `https://yourdomain.com/auth/callback/linkedin`
4. Request access to Sign In with LinkedIn
5. Copy Client ID and Client Secret to `.env`:
   - `LINKEDIN_CLIENT_ID=your_client_id`
   - `LINKEDIN_CLIENT_SECRET=your_client_secret`
6. Required scopes: `r_emailaddress`, `r_liteprofile`"#;

const TWITTER_SETUP_GUIDE: &str = r#"1. Go to https://developer.twitter.com/en/portal/projects-and-apps
2. Create new app (Twitter API v2)
3. Enable OAuth 2.0
4. Add callback URL: `https://yourdomain.com/auth/callback/twitter`
5. Copy Client ID and Client Secret to `.env`:
   - `TWITTER_CLIENT_ID=your_client_id`
   - `TWITTER_CLIENT_SECRET=your_client_secret`
6. Required scopes: `tweet.read`, `users.read`"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::auth_config::{AuthConfigGenerator, InstallMode};
    use crate::security::SecretsManager;

    #[test]
    fn test_django_settings_generation() {
        let mut secrets = SecretsManager::new();
        let config = AuthConfigGenerator::generate(InstallMode::Full, &mut secrets).unwrap();
        let settings = django_settings_toml(&config);

        assert!(settings.contains("SYNTEK_AUTH"));
        assert!(settings.contains("EMAIL_ENCRYPTION_KEY"));
        assert!(settings.contains("RATE_LIMITING"));
    }

    #[test]
    fn test_env_template_generation() {
        let mut secrets = SecretsManager::new();
        let config = AuthConfigGenerator::generate(InstallMode::Full, &mut secrets).unwrap();
        let env = env_template(&config);

        assert!(env.contains("EMAIL_ENCRYPTION_KEY"));
        assert!(env.contains("SECRET_KEY"));
    }

    #[test]
    fn test_readme_generation() {
        let mut secrets = SecretsManager::new();
        let config = AuthConfigGenerator::generate(InstallMode::Full, &mut secrets).unwrap();
        let readme = configuration_readme(&config);

        assert!(readme.contains("Configuration Files"));
        assert!(readme.contains("Setup Steps"));
    }
}
