"""Type stubs for the syntek_pyo3 native extension (PyO3 / maturin build)."""

class DecryptionError(ValueError):
    """Raised when AES-256-GCM decryption of a single field fails."""

    def __init__(self, message: str) -> None: ...

class BatchDecryptionError(ValueError):
    """Raised when one or more fields in a batch decryption operation fail."""

    def __init__(self, field: str, reason: str) -> None: ...

class KeyRing:
    """Versioned key ring for AES-256-GCM field encryption.

    Maps key version numbers (u16, >= 1) to 32-byte AES-256-GCM keys.
    The active encryption key is always the highest version number.
    """

    def __init__(self) -> None: ...
    def add(self, version: int, key: bytes) -> None: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...

def encrypt_field(plaintext: str, ring: KeyRing, model: str, field: str) -> str: ...
def decrypt_field(ciphertext: str, ring: KeyRing, model: str, field: str) -> str: ...
def hash_password(password: str) -> str: ...
def verify_password(password: str, hash: str) -> bool: ...
def encrypt_fields_batch(
    fields: list[tuple[str, str]], ring: KeyRing, model: str
) -> list[str]: ...
def decrypt_fields_batch(
    fields: list[tuple[str, str]], ring: KeyRing, model: str
) -> list[str]: ...
def get_encrypted_field_registry() -> list[tuple[str, str]]: ...

class EncryptedFieldDescriptor:
    model_name: str
    field_name: str
    def __init__(self, model_name: str, field_name: str) -> None: ...

class EncryptedField:
    attname: str
    null: bool
    blank: bool
    def __init__(self, *, null: bool = ..., blank: bool = ...) -> None: ...
    def validate(self, value: str, model_instance: object = ...) -> None: ...
    def from_db_value(
        self,
        value: str | None,
        expression: object,
        connection: object,
    ) -> str | None: ...
    def pre_save(self, instance: object, add: bool) -> str | None: ...
    def contribute_to_class(self, cls: type, name: str) -> None: ...
