"""Type stubs for the syntek_pyo3 native extension (PyO3 / maturin build)."""

def encrypt_field(plaintext: str, key: bytes, model: str, field: str) -> str: ...
def decrypt_field(ciphertext: str, key: bytes, model: str, field: str) -> str: ...
def hash_password(password: str) -> str: ...
def verify_password(password: str, hash: str) -> bool: ...
def encrypt_fields_batch(
    fields: list[tuple[str, str]], key: bytes, model: str
) -> list[str]: ...
def decrypt_fields_batch(
    fields: list[tuple[str, str]], key: bytes, model: str
) -> list[str]: ...

class EncryptedFieldDescriptor:
    model_name: str
    field_name: str
    def __init__(self, model_name: str, field_name: str) -> None: ...

class EncryptedField:
    attname: str
    def __init__(self) -> None: ...
    def validate(self, value: str, model_instance: object = ...) -> None: ...
    def from_db_value(
        self,
        value: str | None,
        expression: object,
        connection: object,
    ) -> str | None: ...
    def pre_save(self, instance: object, add: bool) -> str: ...
    def contribute_to_class(self, cls: type, name: str) -> None: ...
