"""GraphQL types for compliance operations."""

from syntek_graphql_compliance.types.gdpr import (
    AccountDeletionPayload,
    AccountDeletionRequestType,
    CancelAccountDeletionInput,
    ConfirmAccountDeletionInput,
    ConsentPayload,
    ConsentRecordType,
    ConsentType,
    DataExportPayload,
    DataExportRequestType,
    DeletionStatus,
    ExportFormat,
    ExportStatus,
    ProcessingRestrictionInput,
    ProcessingRestrictionPayload,
    ProcessingRestrictionType,
    RequestAccountDeletionInput,
    RequestDataExportInput,
    UpdateConsentInput,
)
from syntek_graphql_compliance.types.legal import (
    AcceptanceMethod,
    AcceptDocumentInput,
    AcceptDocumentPayload,
    AcceptMultipleDocumentsInput,
    AcceptMultipleDocumentsPayload,
    ComplianceStatusType,
    CreateLegalDocumentInput,
    CreateLegalDocumentPayload,
    LegalAcceptanceType,
    LegalDocumentKind,
    LegalDocumentType,
    RegistrationRequirementsType,
)

__all__ = [
    # GDPR types
    "AccountDeletionPayload",
    "AccountDeletionRequestType",
    "CancelAccountDeletionInput",
    "ConfirmAccountDeletionInput",
    "ConsentPayload",
    "ConsentRecordType",
    "ConsentType",
    "DataExportPayload",
    "DataExportRequestType",
    "DeletionStatus",
    "ExportFormat",
    "ExportStatus",
    "ProcessingRestrictionInput",
    "ProcessingRestrictionPayload",
    "ProcessingRestrictionType",
    "RequestAccountDeletionInput",
    "RequestDataExportInput",
    "UpdateConsentInput",
    # Legal types
    "AcceptanceMethod",
    "AcceptDocumentInput",
    "AcceptDocumentPayload",
    "AcceptMultipleDocumentsInput",
    "AcceptMultipleDocumentsPayload",
    "ComplianceStatusType",
    "CreateLegalDocumentInput",
    "CreateLegalDocumentPayload",
    "LegalAcceptanceType",
    "LegalDocumentKind",
    "LegalDocumentType",
    "RegistrationRequirementsType",
]
