//! GraphQL schema installation module
//!
//! Installs Strawberry GraphQL authentication schema.

use crate::config::loader::ProjectConfig;
use crate::utils::error::{CliError, Result};
use crate::utils::exec;
use colored::Colorize;
use indicatif::{ProgressBar, ProgressStyle};
use std::path::Path;

/// GraphQL installer
pub struct GraphQLInstaller;

impl GraphQLInstaller {
    /// Install GraphQL authentication modules
    pub fn install_auth(project_dir: &Path, config: &ProjectConfig) -> Result<Vec<String>> {
        let backend_dir = project_dir.join(&config.backend.directory);
        if !backend_dir.exists() {
            return Err(CliError::InvalidPath(backend_dir));
        }

        println!("{}", "\nInstalling GraphQL authentication modules...".bold());

        let mut installed = Vec::new();

        // GraphQL modules (installed via Python package manager)
        let modules = vec!["syntek-graphql-core", "syntek-graphql-auth"];

        for module in &modules {
            Self::install_module(&backend_dir, module, &config.backend.package_manager)?;
            installed.push(module.to_string());
        }

        Ok(installed)
    }

    /// Install single GraphQL module
    fn install_module(backend_dir: &Path, module: &str, package_manager: &str) -> Result<()> {
        let spinner = ProgressBar::new_spinner();
        spinner.set_style(
            ProgressStyle::default_spinner()
                .template("{spinner:.green} {msg}")
                .unwrap(),
        );
        spinner.set_message(format!("Installing {}...", module.cyan()));
        spinner.enable_steady_tick(std::time::Duration::from_millis(100));

        let result = match package_manager {
            "uv" => exec::run_command("uv", &["pip", "install", module], Some(backend_dir)),
            "pip" => exec::run_command("pip", &["install", module], Some(backend_dir)),
            _ => {
                return Err(CliError::InvalidConfig(format!(
                    "Unsupported package manager: {}",
                    package_manager
                )))
            }
        };

        spinner.finish_and_clear();

        if result.is_ok() {
            println!("{} {}", "✓".green().bold(), module.cyan());
        } else {
            println!("{} {} (failed)", "✗".red().bold(), module.cyan());
        }

        result.map(|_| ())
    }

    /// Generate GraphQL schema boilerplate
    pub fn generate_schema_boilerplate(project_dir: &Path) -> Result<()> {
        println!("{}", "\nGenerating GraphQL schema boilerplate...".bold());

        let schema_content = r#"# GraphQL Schema for Authentication
# Generated by syntek-cli

import strawberry
from syntek_graphql_core.security import (
    QueryDepthLimitExtension,
    QueryComplexityLimitExtension,
    IntrospectionControlExtension,
)
from syntek_graphql_auth.mutations.auth import AuthMutations
from syntek_graphql_auth.queries.user import UserQueries


@strawberry.type
class Query(UserQueries):
    """Root query type"""
    pass


@strawberry.type
class Mutation(AuthMutations):
    """Root mutation type"""
    pass


# Create schema with security extensions
schema = strawberry.Schema(
    query=Query,
    mutation=Mutation,
    extensions=[
        QueryDepthLimitExtension(max_depth=10),
        QueryComplexityLimitExtension(max_complexity=1000),
        IntrospectionControlExtension(),
    ],
)
"#;

        let schema_file = project_dir.join("schema.py");
        std::fs::write(&schema_file, schema_content)?;

        println!(
            "{} GraphQL schema created at {}",
            "✓".green().bold(),
            schema_file.display()
        );

        Ok(())
    }

    /// Generate GraphQL URL configuration
    pub fn generate_url_config(_project_dir: &Path) -> Result<()> {
        println!("{}", "\nAdd GraphQL URL to your Django urls.py:".yellow());

        let url_config = r#"
# Add to your urls.py
from django.urls import path
from strawberry.django.views import AsyncGraphQLView
from .schema import schema

urlpatterns = [
    # ... other urls
    path('graphql/', AsyncGraphQLView.as_view(schema=schema)),
]
"#;

        println!("{}", url_config.cyan());

        Ok(())
    }

    /// Verify GraphQL installation
    pub fn verify_installation(
        project_dir: &Path,
        config: &ProjectConfig,
        modules: &[String],
    ) -> Result<()> {
        println!("{}", "\nVerifying GraphQL installation...".bold());

        let backend_dir = project_dir.join(&config.backend.directory);

        for module in modules {
            // Check if module can be imported
            let check_import = format!("python -c \"import {}\"", module.replace('-', "_"));

            let result = exec::run_command_silent("sh", &["-c", &check_import], Some(&backend_dir));

            if result.is_ok() {
                println!("{} {} can be imported", "✓".green().bold(), module.cyan());
            } else {
                println!(
                    "{} {} cannot be imported",
                    "✗".red().bold(),
                    module.cyan()
                );
                return Err(CliError::SmokeTestFailed(format!(
                    "Module {} import failed",
                    module
                )));
            }
        }

        // Check if schema.py was created
        let schema_file = project_dir.join("schema.py");
        if schema_file.exists() {
            println!("{} schema.py generated", "✓".green().bold());
        } else {
            println!("{}", "Warning: schema.py not found".yellow());
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::loader::ConfigLoader;
    use tempfile::TempDir;

    #[test]
    fn test_generate_schema_boilerplate() {
        let temp_dir = TempDir::new().unwrap();
        let result = GraphQLInstaller::generate_schema_boilerplate(temp_dir.path());
        assert!(result.is_ok());
        assert!(temp_dir.path().join("schema.py").exists());
    }
}
